#!/bin/bash

echo "🚀 AUTOMATIC VERCEL DEPLOYMENT SETUP"
echo "====================================="

echo ""
echo "📋 STEP 1: Push to GitHub"
echo "-------------------------"
echo "git add ."
echo "git commit -m \"Vercel deployment with MongoDB Atlas\""
echo "git push origin main"

echo ""
echo "📋 STEP 2: Deploy Backend to Vercel"
echo "-----------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repository"
echo "4. Set Root Directory: backend"
echo "5. Framework Preset: Other"
echo "6. Add Environment Variables:"
echo "   - NODE_ENV=production"
echo "   - MONGO_URI=mongodb+srv://yasirkhan1_db_user:9920149Yasir@movieapp-cluster.0nvooqy.mongodb.net/movieapp?retryWrites=true&w=majority"
echo "   - JWT_SECRET=movie_app_jwt_secret_key_2024_vercel"
echo "7. Click Deploy"

echo ""
echo "📋 STEP 3: Deploy Frontend to Vercel"
echo "------------------------------------"
echo "1. Click 'New Project' again"
echo "2. Import same repository"
echo "3. Set Root Directory: client"
echo "4. Framework Preset: Create React App"
echo "5. Add Environment Variables:"
echo "   - REACT_APP_API_URL=https://[your-backend-url].vercel.app"
echo "6. Click Deploy"

echo ""
echo "✅ RESULT: Both frontend and backend deployed with database!"
echo "🌐 Your apps will be live at:"
echo "   - Frontend: https://[project-name]-[hash].vercel.app"
echo "   - Backend: https://[project-name]-[hash].vercel.app"

echo ""
echo "🧪 TEST: Visit /health endpoint to verify database connection"