# Netlify Build Configuration for Movie App Frontend

# Build Settings
[build]
  command = "npm run build"
  publish = "client/build"

# Environment Variables
[build.environment]
  REACT_APP_API_URL = "https://moviefinal-backend-khanyasir40.onrender.com"
  REACT_APP_NODE_ENV = "production"
  CI = "false"
  NODE_VERSION = "18"

# Headers for Security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200