[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm ci --only=production']

[phases.build]
cmds = ['echo "Backend ready for deployment"']

[start]
cmd = 'cd backend && node app.js'

[variables]
NODE_ENV = 'production'