[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['echo "Minimal backend ready"']

[start]
cmd = 'cd backend && node minimal.js'

[variables]
NODE_ENV = 'production'