[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm install --only=production']

[phases.build]
cmds = ['echo "Backend deployment ready"']

[start]
cmd = 'cd backend && node server.js'

[variables]
NODE_ENV = 'production'