[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production"

[deploy]
startCommand = "cd backend && node app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "${{ PORT }}"
HOST = "0.0.0.0"