[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --only=production"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "${{ PORT }}"