[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --only=production']

[phases.build]
cmds = ['echo "Backend ready for deployment"']

[start]
cmd = 'node server.js'

[variables]
NODE_ENV = 'production'